language: node_js
node_js:
  - '11.0.0'
cache:
  directories:
    - node_modules
install:
  - yarn install
  - yarn lint --no-fix
  - yarn build
  - yarn test:unit --coverage
  - ./node_modules/.bin/codecov --token="$CODECOV_TOKEN"
